// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	searchoutput "github.com/lgustavopalmieri/healing-specialist/internal/modules/specialist/domain/search/search_output"
	application "github.com/lgustavopalmieri/healing-specialist/internal/modules/specialist/features/search/application"
	gomock "go.uber.org/mock/gomock"
)

type MockSpecialistSearchUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSpecialistSearchUseCaseInterfaceMockRecorder
	isgomock struct{}
}

type MockSpecialistSearchUseCaseInterfaceMockRecorder struct {
	mock *MockSpecialistSearchUseCaseInterface
}

func NewMockSpecialistSearchUseCaseInterface(ctrl *gomock.Controller) *MockSpecialistSearchUseCaseInterface {
	mock := &MockSpecialistSearchUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockSpecialistSearchUseCaseInterfaceMockRecorder{mock}
	return mock
}

func (m *MockSpecialistSearchUseCaseInterface) EXPECT() *MockSpecialistSearchUseCaseInterfaceMockRecorder {
	return m.recorder
}

func (m *MockSpecialistSearchUseCaseInterface) Execute(ctx context.Context, dto *application.SearchSpecialistsDTO) (*searchoutput.ListSearchOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, dto)
	ret0, _ := ret[0].(*searchoutput.ListSearchOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockSpecialistSearchUseCaseInterfaceMockRecorder) Execute(ctx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockSpecialistSearchUseCaseInterface)(nil).Execute), ctx, dto)
}
