// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/auth/features/validate-token/application/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/auth/features/validate-token/application/interface.go -destination=internal/modules/auth/features/validate-token/application/mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBlacklistRepository is a mock of BlacklistRepository interface.
type MockBlacklistRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBlacklistRepositoryMockRecorder
	isgomock struct{}
}

// MockBlacklistRepositoryMockRecorder is the mock recorder for MockBlacklistRepository.
type MockBlacklistRepositoryMockRecorder struct {
	mock *MockBlacklistRepository
}

// NewMockBlacklistRepository creates a new mock instance.
func NewMockBlacklistRepository(ctrl *gomock.Controller) *MockBlacklistRepository {
	mock := &MockBlacklistRepository{ctrl: ctrl}
	mock.recorder = &MockBlacklistRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlacklistRepository) EXPECT() *MockBlacklistRepositoryMockRecorder {
	return m.recorder
}

// IsBlacklisted mocks base method.
func (m *MockBlacklistRepository) IsBlacklisted(ctx context.Context, jti string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBlacklisted", ctx, jti)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsBlacklisted indicates an expected call of IsBlacklisted.
func (mr *MockBlacklistRepositoryMockRecorder) IsBlacklisted(ctx, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBlacklisted", reflect.TypeOf((*MockBlacklistRepository)(nil).IsBlacklisted), ctx, jti)
}
