// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lgustavopalmieri/healing-specialist/pkg/healing-auth/token (interfaces: TokenValidator)
//
// Generated by this command:
//
//	mockgen -destination=internal/modules/auth/features/validate-token/application/mocks/token_validator_mock.go -package=mocks github.com/lgustavopalmieri/healing-specialist/pkg/healing-auth/token TokenValidator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	claims "github.com/lgustavopalmieri/healing-specialist/pkg/healing-auth/claims"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenValidator is a mock of TokenValidator interface.
type MockTokenValidator struct {
	ctrl     *gomock.Controller
	recorder *MockTokenValidatorMockRecorder
	isgomock struct{}
}

// MockTokenValidatorMockRecorder is the mock recorder for MockTokenValidator.
type MockTokenValidatorMockRecorder struct {
	mock *MockTokenValidator
}

// NewMockTokenValidator creates a new mock instance.
func NewMockTokenValidator(ctrl *gomock.Controller) *MockTokenValidator {
	mock := &MockTokenValidator{ctrl: ctrl}
	mock.recorder = &MockTokenValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenValidator) EXPECT() *MockTokenValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockTokenValidator) Validate(ctx context.Context, rawToken string) (*claims.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, rawToken)
	ret0, _ := ret[0].(*claims.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockTokenValidatorMockRecorder) Validate(ctx, rawToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockTokenValidator)(nil).Validate), ctx, rawToken)
}
