// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/auth/features/login/application/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/auth/features/login/application/interface.go -destination=internal/modules/auth/features/login/application/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	audit "github.com/lgustavopalmieri/healing-specialist/internal/modules/auth/domain/audit"
	credential "github.com/lgustavopalmieri/healing-specialist/internal/modules/auth/domain/credential"
	session "github.com/lgustavopalmieri/healing-specialist/internal/modules/auth/domain/session"
	tokenpair "github.com/lgustavopalmieri/healing-specialist/internal/modules/auth/domain/token_pair"
	refreshtoken "github.com/lgustavopalmieri/healing-specialist/internal/modules/auth/shared/repositories/refresh_token"
	provider "github.com/lgustavopalmieri/healing-specialist/pkg/healing-auth/provider"
	role "github.com/lgustavopalmieri/healing-specialist/pkg/healing-auth/role"
	gomock "go.uber.org/mock/gomock"
)

// MockCredentialRepository is a mock of CredentialRepository interface.
type MockCredentialRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialRepositoryMockRecorder
	isgomock struct{}
}

// MockCredentialRepositoryMockRecorder is the mock recorder for MockCredentialRepository.
type MockCredentialRepositoryMockRecorder struct {
	mock *MockCredentialRepository
}

// NewMockCredentialRepository creates a new mock instance.
func NewMockCredentialRepository(ctrl *gomock.Controller) *MockCredentialRepository {
	mock := &MockCredentialRepository{ctrl: ctrl}
	mock.recorder = &MockCredentialRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialRepository) EXPECT() *MockCredentialRepositoryMockRecorder {
	return m.recorder
}

// FindByEmailProviderRole mocks base method.
func (m *MockCredentialRepository) FindByEmailProviderRole(ctx context.Context, email string, p provider.Provider, r role.Role) (*credential.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmailProviderRole", ctx, email, p, r)
	ret0, _ := ret[0].(*credential.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmailProviderRole indicates an expected call of FindByEmailProviderRole.
func (mr *MockCredentialRepositoryMockRecorder) FindByEmailProviderRole(ctx, email, p, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmailProviderRole", reflect.TypeOf((*MockCredentialRepository)(nil).FindByEmailProviderRole), ctx, email, p, r)
}

// UpdateLastUsed mocks base method.
func (m *MockCredentialRepository) UpdateLastUsed(ctx context.Context, credentialID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastUsed", ctx, credentialID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastUsed indicates an expected call of UpdateLastUsed.
func (mr *MockCredentialRepositoryMockRecorder) UpdateLastUsed(ctx, credentialID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastUsed", reflect.TypeOf((*MockCredentialRepository)(nil).UpdateLastUsed), ctx, credentialID)
}

// MockAccessTokenIssuer is a mock of AccessTokenIssuer interface.
type MockAccessTokenIssuer struct {
	ctrl     *gomock.Controller
	recorder *MockAccessTokenIssuerMockRecorder
	isgomock struct{}
}

// MockAccessTokenIssuerMockRecorder is the mock recorder for MockAccessTokenIssuer.
type MockAccessTokenIssuerMockRecorder struct {
	mock *MockAccessTokenIssuer
}

// NewMockAccessTokenIssuer creates a new mock instance.
func NewMockAccessTokenIssuer(ctrl *gomock.Controller) *MockAccessTokenIssuer {
	mock := &MockAccessTokenIssuer{ctrl: ctrl}
	mock.recorder = &MockAccessTokenIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessTokenIssuer) EXPECT() *MockAccessTokenIssuerMockRecorder {
	return m.recorder
}

// IssueAccessAndRefresh mocks base method.
func (m *MockAccessTokenIssuer) IssueAccessAndRefresh(ctx context.Context, c *credential.Credential) (*tokenpair.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueAccessAndRefresh", ctx, c)
	ret0, _ := ret[0].(*tokenpair.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueAccessAndRefresh indicates an expected call of IssueAccessAndRefresh.
func (mr *MockAccessTokenIssuerMockRecorder) IssueAccessAndRefresh(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueAccessAndRefresh", reflect.TypeOf((*MockAccessTokenIssuer)(nil).IssueAccessAndRefresh), ctx, c)
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockSessionRepository) Save(ctx context.Context, s *session.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSessionRepositoryMockRecorder) Save(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSessionRepository)(nil).Save), ctx, s)
}

// MockRefreshTokenRepository is a mock of RefreshTokenRepository interface.
type MockRefreshTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockRefreshTokenRepositoryMockRecorder is the mock recorder for MockRefreshTokenRepository.
type MockRefreshTokenRepositoryMockRecorder struct {
	mock *MockRefreshTokenRepository
}

// NewMockRefreshTokenRepository creates a new mock instance.
func NewMockRefreshTokenRepository(ctrl *gomock.Controller) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockRefreshTokenRepository) Save(ctx context.Context, refreshTokenHash string, payload refreshtoken.RefreshTokenPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, refreshTokenHash, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRefreshTokenRepositoryMockRecorder) Save(ctx, refreshTokenHash, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRefreshTokenRepository)(nil).Save), ctx, refreshTokenHash, payload)
}

// MockLoginAttemptsTracker is a mock of LoginAttemptsTracker interface.
type MockLoginAttemptsTracker struct {
	ctrl     *gomock.Controller
	recorder *MockLoginAttemptsTrackerMockRecorder
	isgomock struct{}
}

// MockLoginAttemptsTrackerMockRecorder is the mock recorder for MockLoginAttemptsTracker.
type MockLoginAttemptsTrackerMockRecorder struct {
	mock *MockLoginAttemptsTracker
}

// NewMockLoginAttemptsTracker creates a new mock instance.
func NewMockLoginAttemptsTracker(ctrl *gomock.Controller) *MockLoginAttemptsTracker {
	mock := &MockLoginAttemptsTracker{ctrl: ctrl}
	mock.recorder = &MockLoginAttemptsTrackerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginAttemptsTracker) EXPECT() *MockLoginAttemptsTrackerMockRecorder {
	return m.recorder
}

// Increment mocks base method.
func (m *MockLoginAttemptsTracker) Increment(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Increment", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// Increment indicates an expected call of Increment.
func (mr *MockLoginAttemptsTrackerMockRecorder) Increment(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Increment", reflect.TypeOf((*MockLoginAttemptsTracker)(nil).Increment), ctx, email)
}

// Reset mocks base method.
func (m *MockLoginAttemptsTracker) Reset(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockLoginAttemptsTrackerMockRecorder) Reset(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockLoginAttemptsTracker)(nil).Reset), ctx, email)
}

// MockAuditRepository is a mock of AuditRepository interface.
type MockAuditRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuditRepositoryMockRecorder
	isgomock struct{}
}

// MockAuditRepositoryMockRecorder is the mock recorder for MockAuditRepository.
type MockAuditRepositoryMockRecorder struct {
	mock *MockAuditRepository
}

// NewMockAuditRepository creates a new mock instance.
func NewMockAuditRepository(ctrl *gomock.Controller) *MockAuditRepository {
	mock := &MockAuditRepository{ctrl: ctrl}
	mock.recorder = &MockAuditRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditRepository) EXPECT() *MockAuditRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockAuditRepository) Save(ctx context.Context, log *audit.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAuditRepositoryMockRecorder) Save(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAuditRepository)(nil).Save), ctx, log)
}
