// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/specialist/features/create/event_listeners/validate_license/listener/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/specialist/features/create/event_listeners/validate_license/listener/interface.go -destination=internal/modules/specialist/features/create/event_listeners/validate_license/listener/mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/lgustavopalmieri/healing-specialist/internal/modules/specialist/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockValidateLicenseRepositoryInterface is a mock of ValidateLicenseRepositoryInterface interface.
type MockValidateLicenseRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockValidateLicenseRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockValidateLicenseRepositoryInterfaceMockRecorder is the mock recorder for MockValidateLicenseRepositoryInterface.
type MockValidateLicenseRepositoryInterfaceMockRecorder struct {
	mock *MockValidateLicenseRepositoryInterface
}

// NewMockValidateLicenseRepositoryInterface creates a new mock instance.
func NewMockValidateLicenseRepositoryInterface(ctrl *gomock.Controller) *MockValidateLicenseRepositoryInterface {
	mock := &MockValidateLicenseRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockValidateLicenseRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidateLicenseRepositoryInterface) EXPECT() *MockValidateLicenseRepositoryInterfaceMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockValidateLicenseRepositoryInterface) FindByID(ctx context.Context, id string) (*domain.Specialist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Specialist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockValidateLicenseRepositoryInterfaceMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockValidateLicenseRepositoryInterface)(nil).FindByID), ctx, id)
}

// UpdateStatus mocks base method.
func (m *MockValidateLicenseRepositoryInterface) UpdateStatus(ctx context.Context, id string, status domain.SpecialistStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockValidateLicenseRepositoryInterfaceMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockValidateLicenseRepositoryInterface)(nil).UpdateStatus), ctx, id, status)
}

// MockLicenseGatewayInterface is a mock of LicenseGatewayInterface interface.
type MockLicenseGatewayInterface struct {
	ctrl     *gomock.Controller
	recorder *MockLicenseGatewayInterfaceMockRecorder
	isgomock struct{}
}

// MockLicenseGatewayInterfaceMockRecorder is the mock recorder for MockLicenseGatewayInterface.
type MockLicenseGatewayInterfaceMockRecorder struct {
	mock *MockLicenseGatewayInterface
}

// NewMockLicenseGatewayInterface creates a new mock instance.
func NewMockLicenseGatewayInterface(ctrl *gomock.Controller) *MockLicenseGatewayInterface {
	mock := &MockLicenseGatewayInterface{ctrl: ctrl}
	mock.recorder = &MockLicenseGatewayInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLicenseGatewayInterface) EXPECT() *MockLicenseGatewayInterfaceMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockLicenseGatewayInterface) Validate(ctx context.Context, licenseNumber string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, licenseNumber)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockLicenseGatewayInterfaceMockRecorder) Validate(ctx, licenseNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockLicenseGatewayInterface)(nil).Validate), ctx, licenseNumber)
}
