// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/specialist/features/update/application/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/specialist/features/update/application/interface.go -destination=internal/modules/specialist/features/update/application/mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/lgustavopalmieri/healing-specialist/internal/modules/specialist/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSpecialistUpdateRepositoryInterface is a mock of SpecialistUpdateRepositoryInterface interface.
type MockSpecialistUpdateRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSpecialistUpdateRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockSpecialistUpdateRepositoryInterfaceMockRecorder is the mock recorder for MockSpecialistUpdateRepositoryInterface.
type MockSpecialistUpdateRepositoryInterfaceMockRecorder struct {
	mock *MockSpecialistUpdateRepositoryInterface
}

// NewMockSpecialistUpdateRepositoryInterface creates a new mock instance.
func NewMockSpecialistUpdateRepositoryInterface(ctrl *gomock.Controller) *MockSpecialistUpdateRepositoryInterface {
	mock := &MockSpecialistUpdateRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockSpecialistUpdateRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpecialistUpdateRepositoryInterface) EXPECT() *MockSpecialistUpdateRepositoryInterfaceMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockSpecialistUpdateRepositoryInterface) FindByID(ctx context.Context, id string) (*domain.Specialist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Specialist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockSpecialistUpdateRepositoryInterfaceMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockSpecialistUpdateRepositoryInterface)(nil).FindByID), ctx, id)
}

// Update mocks base method.
func (m *MockSpecialistUpdateRepositoryInterface) Update(ctx context.Context, specialist *domain.Specialist) (*domain.Specialist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, specialist)
	ret0, _ := ret[0].(*domain.Specialist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSpecialistUpdateRepositoryInterfaceMockRecorder) Update(ctx, specialist any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSpecialistUpdateRepositoryInterface)(nil).Update), ctx, specialist)
}
