// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/specialist/features/update/infra/grpc_service/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/specialist/features/update/infra/grpc_service/service.go -destination=internal/modules/specialist/features/update/infra/grpc_service/mocks/command_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/lgustavopalmieri/healing-specialist/internal/modules/specialist/domain"
	application "github.com/lgustavopalmieri/healing-specialist/internal/modules/specialist/features/update/application"
	gomock "go.uber.org/mock/gomock"
)

// MockSpecialistUpdateCommandInterface is a mock of SpecialistUpdateCommandInterface interface.
type MockSpecialistUpdateCommandInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSpecialistUpdateCommandInterfaceMockRecorder
	isgomock struct{}
}

// MockSpecialistUpdateCommandInterfaceMockRecorder is the mock recorder for MockSpecialistUpdateCommandInterface.
type MockSpecialistUpdateCommandInterfaceMockRecorder struct {
	mock *MockSpecialistUpdateCommandInterface
}

// NewMockSpecialistUpdateCommandInterface creates a new mock instance.
func NewMockSpecialistUpdateCommandInterface(ctrl *gomock.Controller) *MockSpecialistUpdateCommandInterface {
	mock := &MockSpecialistUpdateCommandInterface{ctrl: ctrl}
	mock.recorder = &MockSpecialistUpdateCommandInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpecialistUpdateCommandInterface) EXPECT() *MockSpecialistUpdateCommandInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockSpecialistUpdateCommandInterface) Execute(ctx context.Context, input application.UpdateSpecialistDTO) (*domain.Specialist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*domain.Specialist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockSpecialistUpdateCommandInterfaceMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockSpecialistUpdateCommandInterface)(nil).Execute), ctx, input)
}
