// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/specialist/features/update/adapters/inbound/grpc_service/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/specialist/features/update/adapters/inbound/grpc_service/service.go -destination=internal/modules/specialist/features/update/adapters/inbound/grpc_service/mocks/usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/lgustavopalmieri/healing-specialist/internal/modules/specialist/domain"
	application "github.com/lgustavopalmieri/healing-specialist/internal/modules/specialist/features/update/application"
	gomock "go.uber.org/mock/gomock"
)

// MockSpecialistUpdateUseCaseInterface is a mock of SpecialistUpdateUseCaseInterface interface.
type MockSpecialistUpdateUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSpecialistUpdateUseCaseInterfaceMockRecorder
	isgomock struct{}
}

// MockSpecialistUpdateUseCaseInterfaceMockRecorder is the mock recorder for MockSpecialistUpdateUseCaseInterface.
type MockSpecialistUpdateUseCaseInterfaceMockRecorder struct {
	mock *MockSpecialistUpdateUseCaseInterface
}

// NewMockSpecialistUpdateUseCaseInterface creates a new mock instance.
func NewMockSpecialistUpdateUseCaseInterface(ctrl *gomock.Controller) *MockSpecialistUpdateUseCaseInterface {
	mock := &MockSpecialistUpdateUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockSpecialistUpdateUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpecialistUpdateUseCaseInterface) EXPECT() *MockSpecialistUpdateUseCaseInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockSpecialistUpdateUseCaseInterface) Execute(ctx context.Context, input application.UpdateSpecialistDTO) (*domain.Specialist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*domain.Specialist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockSpecialistUpdateUseCaseInterfaceMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockSpecialistUpdateUseCaseInterface)(nil).Execute), ctx, input)
}
