// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/auth/features/refresh-token/application/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/auth/features/refresh-token/application/interface.go -destination=internal/modules/auth/features/refresh-token/application/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	credential "github.com/lgustavopalmieri/healing-specialist/internal/modules/auth/domain/credential"
	tokenpair "github.com/lgustavopalmieri/healing-specialist/internal/modules/auth/domain/token_pair"
	refreshtoken "github.com/lgustavopalmieri/healing-specialist/internal/modules/auth/shared/repositories/refresh_token"
	role "github.com/lgustavopalmieri/healing-specialist/pkg/healing-auth/role"
	gomock "go.uber.org/mock/gomock"
)

// MockRefreshTokenRepository is a mock of RefreshTokenRepository interface.
type MockRefreshTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockRefreshTokenRepositoryMockRecorder is the mock recorder for MockRefreshTokenRepository.
type MockRefreshTokenRepositoryMockRecorder struct {
	mock *MockRefreshTokenRepository
}

// NewMockRefreshTokenRepository creates a new mock instance.
func NewMockRefreshTokenRepository(ctrl *gomock.Controller) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockRefreshTokenRepository) Delete(ctx context.Context, refreshTokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, refreshTokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRefreshTokenRepositoryMockRecorder) Delete(ctx, refreshTokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRefreshTokenRepository)(nil).Delete), ctx, refreshTokenHash)
}

// Find mocks base method.
func (m *MockRefreshTokenRepository) Find(ctx context.Context, refreshTokenHash string) (*refreshtoken.RefreshTokenPayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, refreshTokenHash)
	ret0, _ := ret[0].(*refreshtoken.RefreshTokenPayload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRefreshTokenRepositoryMockRecorder) Find(ctx, refreshTokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRefreshTokenRepository)(nil).Find), ctx, refreshTokenHash)
}

// Save mocks base method.
func (m *MockRefreshTokenRepository) Save(ctx context.Context, refreshTokenHash string, payload refreshtoken.RefreshTokenPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, refreshTokenHash, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRefreshTokenRepositoryMockRecorder) Save(ctx, refreshTokenHash, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRefreshTokenRepository)(nil).Save), ctx, refreshTokenHash, payload)
}

// MockAccessTokenIssuer is a mock of AccessTokenIssuer interface.
type MockAccessTokenIssuer struct {
	ctrl     *gomock.Controller
	recorder *MockAccessTokenIssuerMockRecorder
	isgomock struct{}
}

// MockAccessTokenIssuerMockRecorder is the mock recorder for MockAccessTokenIssuer.
type MockAccessTokenIssuerMockRecorder struct {
	mock *MockAccessTokenIssuer
}

// NewMockAccessTokenIssuer creates a new mock instance.
func NewMockAccessTokenIssuer(ctrl *gomock.Controller) *MockAccessTokenIssuer {
	mock := &MockAccessTokenIssuer{ctrl: ctrl}
	mock.recorder = &MockAccessTokenIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessTokenIssuer) EXPECT() *MockAccessTokenIssuerMockRecorder {
	return m.recorder
}

// IssueAccessAndRefresh mocks base method.
func (m *MockAccessTokenIssuer) IssueAccessAndRefresh(ctx context.Context, c *credential.Credential) (*tokenpair.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueAccessAndRefresh", ctx, c)
	ret0, _ := ret[0].(*tokenpair.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueAccessAndRefresh indicates an expected call of IssueAccessAndRefresh.
func (mr *MockAccessTokenIssuerMockRecorder) IssueAccessAndRefresh(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueAccessAndRefresh", reflect.TypeOf((*MockAccessTokenIssuer)(nil).IssueAccessAndRefresh), ctx, c)
}

// MockCredentialRepository is a mock of CredentialRepository interface.
type MockCredentialRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialRepositoryMockRecorder
	isgomock struct{}
}

// MockCredentialRepositoryMockRecorder is the mock recorder for MockCredentialRepository.
type MockCredentialRepositoryMockRecorder struct {
	mock *MockCredentialRepository
}

// NewMockCredentialRepository creates a new mock instance.
func NewMockCredentialRepository(ctrl *gomock.Controller) *MockCredentialRepository {
	mock := &MockCredentialRepository{ctrl: ctrl}
	mock.recorder = &MockCredentialRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialRepository) EXPECT() *MockCredentialRepositoryMockRecorder {
	return m.recorder
}

// FindBySubjectAndRole mocks base method.
func (m *MockCredentialRepository) FindBySubjectAndRole(ctx context.Context, subjectID string, r role.Role) (*credential.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySubjectAndRole", ctx, subjectID, r)
	ret0, _ := ret[0].(*credential.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySubjectAndRole indicates an expected call of FindBySubjectAndRole.
func (mr *MockCredentialRepositoryMockRecorder) FindBySubjectAndRole(ctx, subjectID, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySubjectAndRole", reflect.TypeOf((*MockCredentialRepository)(nil).FindBySubjectAndRole), ctx, subjectID, r)
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// UpdateRefreshTokenHash mocks base method.
func (m *MockSessionRepository) UpdateRefreshTokenHash(ctx context.Context, sessionID, newHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRefreshTokenHash", ctx, sessionID, newHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRefreshTokenHash indicates an expected call of UpdateRefreshTokenHash.
func (mr *MockSessionRepositoryMockRecorder) UpdateRefreshTokenHash(ctx, sessionID, newHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRefreshTokenHash", reflect.TypeOf((*MockSessionRepository)(nil).UpdateRefreshTokenHash), ctx, sessionID, newHash)
}
