// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: update_specialist.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UpdateSpecialistService_UpdateSpecialist_FullMethodName = "/updatepb.UpdateSpecialistService/UpdateSpecialist"
)

// UpdateSpecialistServiceClient is the client API for UpdateSpecialistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpdateSpecialistServiceClient interface {
	UpdateSpecialist(ctx context.Context, in *UpdateSpecialistRequest, opts ...grpc.CallOption) (*UpdateSpecialistResponse, error)
}

type updateSpecialistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUpdateSpecialistServiceClient(cc grpc.ClientConnInterface) UpdateSpecialistServiceClient {
	return &updateSpecialistServiceClient{cc}
}

func (c *updateSpecialistServiceClient) UpdateSpecialist(ctx context.Context, in *UpdateSpecialistRequest, opts ...grpc.CallOption) (*UpdateSpecialistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSpecialistResponse)
	err := c.cc.Invoke(ctx, UpdateSpecialistService_UpdateSpecialist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateSpecialistServiceServer is the server API for UpdateSpecialistService service.
// All implementations must embed UnimplementedUpdateSpecialistServiceServer
// for forward compatibility.
type UpdateSpecialistServiceServer interface {
	UpdateSpecialist(context.Context, *UpdateSpecialistRequest) (*UpdateSpecialistResponse, error)
	mustEmbedUnimplementedUpdateSpecialistServiceServer()
}

// UnimplementedUpdateSpecialistServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpdateSpecialistServiceServer struct{}

func (UnimplementedUpdateSpecialistServiceServer) UpdateSpecialist(context.Context, *UpdateSpecialistRequest) (*UpdateSpecialistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSpecialist not implemented")
}
func (UnimplementedUpdateSpecialistServiceServer) mustEmbedUnimplementedUpdateSpecialistServiceServer() {
}
func (UnimplementedUpdateSpecialistServiceServer) testEmbeddedByValue() {}

// UnsafeUpdateSpecialistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpdateSpecialistServiceServer will
// result in compilation errors.
type UnsafeUpdateSpecialistServiceServer interface {
	mustEmbedUnimplementedUpdateSpecialistServiceServer()
}

func RegisterUpdateSpecialistServiceServer(s grpc.ServiceRegistrar, srv UpdateSpecialistServiceServer) {
	// If the following call panics, it indicates UnimplementedUpdateSpecialistServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UpdateSpecialistService_ServiceDesc, srv)
}

func _UpdateSpecialistService_UpdateSpecialist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSpecialistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateSpecialistServiceServer).UpdateSpecialist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpdateSpecialistService_UpdateSpecialist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateSpecialistServiceServer).UpdateSpecialist(ctx, req.(*UpdateSpecialistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UpdateSpecialistService_ServiceDesc is the grpc.ServiceDesc for UpdateSpecialistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpdateSpecialistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "updatepb.UpdateSpecialistService",
	HandlerType: (*UpdateSpecialistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateSpecialist",
			Handler:    _UpdateSpecialistService_UpdateSpecialist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "update_specialist.proto",
}
