// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: update_specialist.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Specialist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Specialty     string                 `protobuf:"bytes,5,opt,name=specialty,proto3" json:"specialty,omitempty"`
	LicenseNumber string                 `protobuf:"bytes,6,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Keywords      []string               `protobuf:"bytes,8,rep,name=keywords,proto3" json:"keywords,omitempty"`
	AgreedToShare bool                   `protobuf:"varint,9,opt,name=agreed_to_share,json=agreedToShare,proto3" json:"agreed_to_share,omitempty"`
	Rating        float64                `protobuf:"fixed64,10,opt,name=rating,proto3" json:"rating,omitempty"`
	Status        string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Specialist) Reset() {
	*x = Specialist{}
	mi := &file_update_specialist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Specialist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specialist) ProtoMessage() {}

func (x *Specialist) ProtoReflect() protoreflect.Message {
	mi := &file_update_specialist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specialist.ProtoReflect.Descriptor instead.
func (*Specialist) Descriptor() ([]byte, []int) {
	return file_update_specialist_proto_rawDescGZIP(), []int{0}
}

func (x *Specialist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Specialist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Specialist) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Specialist) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Specialist) GetSpecialty() string {
	if x != nil {
		return x.Specialty
	}
	return ""
}

func (x *Specialist) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *Specialist) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Specialist) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *Specialist) GetAgreedToShare() bool {
	if x != nil {
		return x.AgreedToShare
	}
	return false
}

func (x *Specialist) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Specialist) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Specialist) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Specialist) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UpdateSpecialistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *wrappers.StringValue  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         *wrappers.StringValue  `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         *wrappers.StringValue  `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Specialty     *wrappers.StringValue  `protobuf:"bytes,5,opt,name=specialty,proto3" json:"specialty,omitempty"`
	LicenseNumber *wrappers.StringValue  `protobuf:"bytes,6,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	Description   *wrappers.StringValue  `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Keywords      []string               `protobuf:"bytes,8,rep,name=keywords,proto3" json:"keywords,omitempty"`
	AgreedToShare *wrappers.BoolValue    `protobuf:"bytes,9,opt,name=agreed_to_share,json=agreedToShare,proto3" json:"agreed_to_share,omitempty"`
	Status        *wrappers.StringValue  `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSpecialistRequest) Reset() {
	*x = UpdateSpecialistRequest{}
	mi := &file_update_specialist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSpecialistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSpecialistRequest) ProtoMessage() {}

func (x *UpdateSpecialistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_update_specialist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSpecialistRequest.ProtoReflect.Descriptor instead.
func (*UpdateSpecialistRequest) Descriptor() ([]byte, []int) {
	return file_update_specialist_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateSpecialistRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSpecialistRequest) GetName() *wrappers.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateSpecialistRequest) GetEmail() *wrappers.StringValue {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *UpdateSpecialistRequest) GetPhone() *wrappers.StringValue {
	if x != nil {
		return x.Phone
	}
	return nil
}

func (x *UpdateSpecialistRequest) GetSpecialty() *wrappers.StringValue {
	if x != nil {
		return x.Specialty
	}
	return nil
}

func (x *UpdateSpecialistRequest) GetLicenseNumber() *wrappers.StringValue {
	if x != nil {
		return x.LicenseNumber
	}
	return nil
}

func (x *UpdateSpecialistRequest) GetDescription() *wrappers.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *UpdateSpecialistRequest) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *UpdateSpecialistRequest) GetAgreedToShare() *wrappers.BoolValue {
	if x != nil {
		return x.AgreedToShare
	}
	return nil
}

func (x *UpdateSpecialistRequest) GetStatus() *wrappers.StringValue {
	if x != nil {
		return x.Status
	}
	return nil
}

type UpdateSpecialistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Specialist    *Specialist            `protobuf:"bytes,1,opt,name=specialist,proto3" json:"specialist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSpecialistResponse) Reset() {
	*x = UpdateSpecialistResponse{}
	mi := &file_update_specialist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSpecialistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSpecialistResponse) ProtoMessage() {}

func (x *UpdateSpecialistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_update_specialist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSpecialistResponse.ProtoReflect.Descriptor instead.
func (*UpdateSpecialistResponse) Descriptor() ([]byte, []int) {
	return file_update_specialist_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateSpecialistResponse) GetSpecialist() *Specialist {
	if x != nil {
		return x.Specialist
	}
	return nil
}

var File_update_specialist_proto protoreflect.FileDescriptor

const file_update_specialist_proto_rawDesc = "" +
	"\n" +
	"\x17update_specialist.proto\x12\bupdatepb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xad\x03\n" +
	"\n" +
	"Specialist\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1c\n" +
	"\tspecialty\x18\x05 \x01(\tR\tspecialty\x12%\n" +
	"\x0elicense_number\x18\x06 \x01(\tR\rlicenseNumber\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1a\n" +
	"\bkeywords\x18\b \x03(\tR\bkeywords\x12&\n" +
	"\x0fagreed_to_share\x18\t \x01(\bR\ragreedToShare\x12\x16\n" +
	"\x06rating\x18\n" +
	" \x01(\x01R\x06rating\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9a\x04\n" +
	"\x17UpdateSpecialistRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x04name\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x04name\x122\n" +
	"\x05email\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x05email\x122\n" +
	"\x05phone\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x05phone\x12:\n" +
	"\tspecialty\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\tspecialty\x12C\n" +
	"\x0elicense_number\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\rlicenseNumber\x12>\n" +
	"\vdescription\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x12\x1a\n" +
	"\bkeywords\x18\b \x03(\tR\bkeywords\x12B\n" +
	"\x0fagreed_to_share\x18\t \x01(\v2\x1a.google.protobuf.BoolValueR\ragreedToShare\x124\n" +
	"\x06status\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueR\x06status\"P\n" +
	"\x18UpdateSpecialistResponse\x124\n" +
	"\n" +
	"specialist\x18\x01 \x01(\v2\x14.updatepb.SpecialistR\n" +
	"specialist2v\n" +
	"\x17UpdateSpecialistService\x12[\n" +
	"\x10UpdateSpecialist\x12!.updatepb.UpdateSpecialistRequest\x1a\".updatepb.UpdateSpecialistResponse\"\x00B\x06Z\x04./pbb\x06proto3"

var (
	file_update_specialist_proto_rawDescOnce sync.Once
	file_update_specialist_proto_rawDescData []byte
)

func file_update_specialist_proto_rawDescGZIP() []byte {
	file_update_specialist_proto_rawDescOnce.Do(func() {
		file_update_specialist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_update_specialist_proto_rawDesc), len(file_update_specialist_proto_rawDesc)))
	})
	return file_update_specialist_proto_rawDescData
}

var file_update_specialist_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_update_specialist_proto_goTypes = []any{
	(*Specialist)(nil),               // 0: updatepb.Specialist
	(*UpdateSpecialistRequest)(nil),  // 1: updatepb.UpdateSpecialistRequest
	(*UpdateSpecialistResponse)(nil), // 2: updatepb.UpdateSpecialistResponse
	(*timestamp.Timestamp)(nil),      // 3: google.protobuf.Timestamp
	(*wrappers.StringValue)(nil),     // 4: google.protobuf.StringValue
	(*wrappers.BoolValue)(nil),       // 5: google.protobuf.BoolValue
}
var file_update_specialist_proto_depIdxs = []int32{
	3,  // 0: updatepb.Specialist.created_at:type_name -> google.protobuf.Timestamp
	3,  // 1: updatepb.Specialist.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 2: updatepb.UpdateSpecialistRequest.name:type_name -> google.protobuf.StringValue
	4,  // 3: updatepb.UpdateSpecialistRequest.email:type_name -> google.protobuf.StringValue
	4,  // 4: updatepb.UpdateSpecialistRequest.phone:type_name -> google.protobuf.StringValue
	4,  // 5: updatepb.UpdateSpecialistRequest.specialty:type_name -> google.protobuf.StringValue
	4,  // 6: updatepb.UpdateSpecialistRequest.license_number:type_name -> google.protobuf.StringValue
	4,  // 7: updatepb.UpdateSpecialistRequest.description:type_name -> google.protobuf.StringValue
	5,  // 8: updatepb.UpdateSpecialistRequest.agreed_to_share:type_name -> google.protobuf.BoolValue
	4,  // 9: updatepb.UpdateSpecialistRequest.status:type_name -> google.protobuf.StringValue
	0,  // 10: updatepb.UpdateSpecialistResponse.specialist:type_name -> updatepb.Specialist
	1,  // 11: updatepb.UpdateSpecialistService.UpdateSpecialist:input_type -> updatepb.UpdateSpecialistRequest
	2,  // 12: updatepb.UpdateSpecialistService.UpdateSpecialist:output_type -> updatepb.UpdateSpecialistResponse
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_update_specialist_proto_init() }
func file_update_specialist_proto_init() {
	if File_update_specialist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_update_specialist_proto_rawDesc), len(file_update_specialist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_update_specialist_proto_goTypes,
		DependencyIndexes: file_update_specialist_proto_depIdxs,
		MessageInfos:      file_update_specialist_proto_msgTypes,
	}.Build()
	File_update_specialist_proto = out.File
	file_update_specialist_proto_goTypes = nil
	file_update_specialist_proto_depIdxs = nil
}
