// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/specialist/features/search/application/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/specialist/features/search/application/interface.go -destination=internal/modules/specialist/features/search/application/mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	searchinput "github.com/lgustavopalmieri/healing-specialist/internal/modules/specialist/domain/search/search_input"
	searchoutput "github.com/lgustavopalmieri/healing-specialist/internal/modules/specialist/domain/search/search_output"
	gomock "go.uber.org/mock/gomock"
)

// MockSpecialistSearchRepositoryInterface is a mock of SpecialistSearchRepositoryInterface interface.
type MockSpecialistSearchRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSpecialistSearchRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockSpecialistSearchRepositoryInterfaceMockRecorder is the mock recorder for MockSpecialistSearchRepositoryInterface.
type MockSpecialistSearchRepositoryInterfaceMockRecorder struct {
	mock *MockSpecialistSearchRepositoryInterface
}

// NewMockSpecialistSearchRepositoryInterface creates a new mock instance.
func NewMockSpecialistSearchRepositoryInterface(ctrl *gomock.Controller) *MockSpecialistSearchRepositoryInterface {
	mock := &MockSpecialistSearchRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockSpecialistSearchRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpecialistSearchRepositoryInterface) EXPECT() *MockSpecialistSearchRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockSpecialistSearchRepositoryInterface) Search(ctx context.Context, input *searchinput.ListSearchInput) (*searchoutput.ListSearchOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, input)
	ret0, _ := ret[0].(*searchoutput.ListSearchOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSpecialistSearchRepositoryInterfaceMockRecorder) Search(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSpecialistSearchRepositoryInterface)(nil).Search), ctx, input)
}
