// Code generated by MockGen. DO NOT EDIT.
package mocks

import (
	context "context"
	reflect "reflect"

	searchinput "github.com/lgustavopalmieri/healing-specialist/internal/modules/specialist/domain/search/search_input"
	searchoutput "github.com/lgustavopalmieri/healing-specialist/internal/modules/specialist/domain/search/search_output"
	gomock "go.uber.org/mock/gomock"
)

type MockSpecialistSearchRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSpecialistSearchRepositoryInterfaceMockRecorder
	isgomock struct{}
}

type MockSpecialistSearchRepositoryInterfaceMockRecorder struct {
	mock *MockSpecialistSearchRepositoryInterface
}

func NewMockSpecialistSearchRepositoryInterface(ctrl *gomock.Controller) *MockSpecialistSearchRepositoryInterface {
	mock := &MockSpecialistSearchRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockSpecialistSearchRepositoryInterfaceMockRecorder{mock}
	return mock
}

func (m *MockSpecialistSearchRepositoryInterface) EXPECT() *MockSpecialistSearchRepositoryInterfaceMockRecorder {
	return m.recorder
}

func (m *MockSpecialistSearchRepositoryInterface) Search(ctx context.Context, input *searchinput.ListSearchInput) (*searchoutput.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, input)
	ret0, _ := ret[0].(*searchoutput.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockSpecialistSearchRepositoryInterfaceMockRecorder) Search(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSpecialistSearchRepositoryInterface)(nil).Search), ctx, input)
}
