// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/specialist/features/create/application/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/specialist/features/create/application/interface.go -destination=internal/modules/specialist/features/create/application/mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/lgustavopalmieri/healing-specialist/internal/modules/specialist/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSpecialistCreateRepositoryInterface is a mock of SpecialistCreateRepositoryInterface interface.
type MockSpecialistCreateRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSpecialistCreateRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockSpecialistCreateRepositoryInterfaceMockRecorder is the mock recorder for MockSpecialistCreateRepositoryInterface.
type MockSpecialistCreateRepositoryInterfaceMockRecorder struct {
	mock *MockSpecialistCreateRepositoryInterface
}

// NewMockSpecialistCreateRepositoryInterface creates a new mock instance.
func NewMockSpecialistCreateRepositoryInterface(ctrl *gomock.Controller) *MockSpecialistCreateRepositoryInterface {
	mock := &MockSpecialistCreateRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockSpecialistCreateRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpecialistCreateRepositoryInterface) EXPECT() *MockSpecialistCreateRepositoryInterfaceMockRecorder {
	return m.recorder
}

// SaveWithValidation mocks base method.
func (m *MockSpecialistCreateRepositoryInterface) SaveWithValidation(ctx context.Context, specialist *domain.Specialist) (*domain.Specialist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveWithValidation", ctx, specialist)
	ret0, _ := ret[0].(*domain.Specialist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveWithValidation indicates an expected call of SaveWithValidation.
func (mr *MockSpecialistCreateRepositoryInterfaceMockRecorder) SaveWithValidation(ctx, specialist any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveWithValidation", reflect.TypeOf((*MockSpecialistCreateRepositoryInterface)(nil).SaveWithValidation), ctx, specialist)
}
