// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/specialist/features/create/application/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/specialist/features/create/application/interface.go -destination=internal/modules/specialist/features/create/application/mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/lgustavopalmieri/healing-specialist/internal/modules/specialist/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSpecialistCreateRepositoryInterface is a mock of SpecialistCreateRepositoryInterface interface.
type MockSpecialistCreateRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSpecialistCreateRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockSpecialistCreateRepositoryInterfaceMockRecorder is the mock recorder for MockSpecialistCreateRepositoryInterface.
type MockSpecialistCreateRepositoryInterfaceMockRecorder struct {
	mock *MockSpecialistCreateRepositoryInterface
}

// NewMockSpecialistCreateRepositoryInterface creates a new mock instance.
func NewMockSpecialistCreateRepositoryInterface(ctrl *gomock.Controller) *MockSpecialistCreateRepositoryInterface {
	mock := &MockSpecialistCreateRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockSpecialistCreateRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpecialistCreateRepositoryInterface) EXPECT() *MockSpecialistCreateRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockSpecialistCreateRepositoryInterface) Save(ctx context.Context, specialist *domain.Specialist) (*domain.Specialist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, specialist)
	ret0, _ := ret[0].(*domain.Specialist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockSpecialistCreateRepositoryInterfaceMockRecorder) Save(ctx, specialist any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSpecialistCreateRepositoryInterface)(nil).Save), ctx, specialist)
}

// ValidateUniqueness mocks base method.
func (m *MockSpecialistCreateRepositoryInterface) ValidateUniqueness(ctx context.Context, id, email, licenseNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateUniqueness", ctx, id, email, licenseNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateUniqueness indicates an expected call of ValidateUniqueness.
func (mr *MockSpecialistCreateRepositoryInterfaceMockRecorder) ValidateUniqueness(ctx, id, email, licenseNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateUniqueness", reflect.TypeOf((*MockSpecialistCreateRepositoryInterface)(nil).ValidateUniqueness), ctx, id, email, licenseNumber)
}

// MockSpecialistCreateExternalGatewayInterface is a mock of SpecialistCreateExternalGatewayInterface interface.
type MockSpecialistCreateExternalGatewayInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSpecialistCreateExternalGatewayInterfaceMockRecorder
	isgomock struct{}
}

// MockSpecialistCreateExternalGatewayInterfaceMockRecorder is the mock recorder for MockSpecialistCreateExternalGatewayInterface.
type MockSpecialistCreateExternalGatewayInterfaceMockRecorder struct {
	mock *MockSpecialistCreateExternalGatewayInterface
}

// NewMockSpecialistCreateExternalGatewayInterface creates a new mock instance.
func NewMockSpecialistCreateExternalGatewayInterface(ctrl *gomock.Controller) *MockSpecialistCreateExternalGatewayInterface {
	mock := &MockSpecialistCreateExternalGatewayInterface{ctrl: ctrl}
	mock.recorder = &MockSpecialistCreateExternalGatewayInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpecialistCreateExternalGatewayInterface) EXPECT() *MockSpecialistCreateExternalGatewayInterfaceMockRecorder {
	return m.recorder
}

// ValidateLicenseNumber mocks base method.
func (m *MockSpecialistCreateExternalGatewayInterface) ValidateLicenseNumber(ctx context.Context, licenseNumber string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateLicenseNumber", ctx, licenseNumber)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateLicenseNumber indicates an expected call of ValidateLicenseNumber.
func (mr *MockSpecialistCreateExternalGatewayInterfaceMockRecorder) ValidateLicenseNumber(ctx, licenseNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateLicenseNumber", reflect.TypeOf((*MockSpecialistCreateExternalGatewayInterface)(nil).ValidateLicenseNumber), ctx, licenseNumber)
}
