// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/healing-auth/middleware/shared/interface.go
//
// Generated by this command:
//
//	mockgen -source=pkg/healing-auth/middleware/shared/interface.go -destination=pkg/healing-auth/middleware/shared/mocks/validate_token_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	claims "github.com/lgustavopalmieri/healing-specialist/pkg/healing-auth/claims"
	gomock "go.uber.org/mock/gomock"
)

// MockValidateTokenUseCase is a mock of ValidateTokenUseCase interface.
type MockValidateTokenUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockValidateTokenUseCaseMockRecorder
	isgomock struct{}
}

// MockValidateTokenUseCaseMockRecorder is the mock recorder for MockValidateTokenUseCase.
type MockValidateTokenUseCaseMockRecorder struct {
	mock *MockValidateTokenUseCase
}

// NewMockValidateTokenUseCase creates a new mock instance.
func NewMockValidateTokenUseCase(ctrl *gomock.Controller) *MockValidateTokenUseCase {
	mock := &MockValidateTokenUseCase{ctrl: ctrl}
	mock.recorder = &MockValidateTokenUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidateTokenUseCase) EXPECT() *MockValidateTokenUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockValidateTokenUseCase) Execute(ctx context.Context, rawToken string) (*claims.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, rawToken)
	ret0, _ := ret[0].(*claims.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockValidateTokenUseCaseMockRecorder) Execute(ctx, rawToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockValidateTokenUseCase)(nil).Execute), ctx, rawToken)
}
