// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/specialist.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Specialist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Specialty     string                 `protobuf:"bytes,5,opt,name=specialty,proto3" json:"specialty,omitempty"`
	LicenseNumber string                 `protobuf:"bytes,6,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Keywords      []string               `protobuf:"bytes,8,rep,name=keywords,proto3" json:"keywords,omitempty"`
	AgreedToShare bool                   `protobuf:"varint,9,opt,name=agreed_to_share,json=agreedToShare,proto3" json:"agreed_to_share,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Specialist) Reset() {
	*x = Specialist{}
	mi := &file_proto_specialist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Specialist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specialist) ProtoMessage() {}

func (x *Specialist) ProtoReflect() protoreflect.Message {
	mi := &file_proto_specialist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specialist.ProtoReflect.Descriptor instead.
func (*Specialist) Descriptor() ([]byte, []int) {
	return file_proto_specialist_proto_rawDescGZIP(), []int{0}
}

func (x *Specialist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Specialist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Specialist) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Specialist) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Specialist) GetSpecialty() string {
	if x != nil {
		return x.Specialty
	}
	return ""
}

func (x *Specialist) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *Specialist) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Specialist) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *Specialist) GetAgreedToShare() bool {
	if x != nil {
		return x.AgreedToShare
	}
	return false
}

func (x *Specialist) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Specialist) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateSpecialistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Specialty     string                 `protobuf:"bytes,4,opt,name=specialty,proto3" json:"specialty,omitempty"`
	LicenseNumber string                 `protobuf:"bytes,5,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Keywords      []string               `protobuf:"bytes,7,rep,name=keywords,proto3" json:"keywords,omitempty"`
	AgreedToShare bool                   `protobuf:"varint,8,opt,name=agreed_to_share,json=agreedToShare,proto3" json:"agreed_to_share,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSpecialistRequest) Reset() {
	*x = CreateSpecialistRequest{}
	mi := &file_proto_specialist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSpecialistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpecialistRequest) ProtoMessage() {}

func (x *CreateSpecialistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_specialist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpecialistRequest.ProtoReflect.Descriptor instead.
func (*CreateSpecialistRequest) Descriptor() ([]byte, []int) {
	return file_proto_specialist_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSpecialistRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSpecialistRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateSpecialistRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateSpecialistRequest) GetSpecialty() string {
	if x != nil {
		return x.Specialty
	}
	return ""
}

func (x *CreateSpecialistRequest) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *CreateSpecialistRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSpecialistRequest) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *CreateSpecialistRequest) GetAgreedToShare() bool {
	if x != nil {
		return x.AgreedToShare
	}
	return false
}

type CreateSpecialistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Specialist    *Specialist            `protobuf:"bytes,1,opt,name=specialist,proto3" json:"specialist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSpecialistResponse) Reset() {
	*x = CreateSpecialistResponse{}
	mi := &file_proto_specialist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSpecialistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpecialistResponse) ProtoMessage() {}

func (x *CreateSpecialistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_specialist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpecialistResponse.ProtoReflect.Descriptor instead.
func (*CreateSpecialistResponse) Descriptor() ([]byte, []int) {
	return file_proto_specialist_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSpecialistResponse) GetSpecialist() *Specialist {
	if x != nil {
		return x.Specialist
	}
	return nil
}

var File_proto_specialist_proto protoreflect.FileDescriptor

const file_proto_specialist_proto_rawDesc = "" +
	"\n" +
	"\x16proto/specialist.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfd\x02\n" +
	"\n" +
	"Specialist\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1c\n" +
	"\tspecialty\x18\x05 \x01(\tR\tspecialty\x12%\n" +
	"\x0elicense_number\x18\x06 \x01(\tR\rlicenseNumber\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1a\n" +
	"\bkeywords\x18\b \x03(\tR\bkeywords\x12&\n" +
	"\x0fagreed_to_share\x18\t \x01(\bR\ragreedToShare\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x84\x02\n" +
	"\x17CreateSpecialistRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1c\n" +
	"\tspecialty\x18\x04 \x01(\tR\tspecialty\x12%\n" +
	"\x0elicense_number\x18\x05 \x01(\tR\rlicenseNumber\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1a\n" +
	"\bkeywords\x18\a \x03(\tR\bkeywords\x12&\n" +
	"\x0fagreed_to_share\x18\b \x01(\bR\ragreedToShare\"J\n" +
	"\x18CreateSpecialistResponse\x12.\n" +
	"\n" +
	"specialist\x18\x01 \x01(\v2\x0e.pb.SpecialistR\n" +
	"specialist2d\n" +
	"\x11SpecialistService\x12O\n" +
	"\x10CreateSpecialist\x12\x1b.pb.CreateSpecialistRequest\x1a\x1c.pb.CreateSpecialistResponse\"\x00B\x06Z\x04./pbb\x06proto3"

var (
	file_proto_specialist_proto_rawDescOnce sync.Once
	file_proto_specialist_proto_rawDescData []byte
)

func file_proto_specialist_proto_rawDescGZIP() []byte {
	file_proto_specialist_proto_rawDescOnce.Do(func() {
		file_proto_specialist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_specialist_proto_rawDesc), len(file_proto_specialist_proto_rawDesc)))
	})
	return file_proto_specialist_proto_rawDescData
}

var file_proto_specialist_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_specialist_proto_goTypes = []any{
	(*Specialist)(nil),               // 0: pb.Specialist
	(*CreateSpecialistRequest)(nil),  // 1: pb.CreateSpecialistRequest
	(*CreateSpecialistResponse)(nil), // 2: pb.CreateSpecialistResponse
	(*timestamp.Timestamp)(nil),      // 3: google.protobuf.Timestamp
}
var file_proto_specialist_proto_depIdxs = []int32{
	3, // 0: pb.Specialist.created_at:type_name -> google.protobuf.Timestamp
	3, // 1: pb.Specialist.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: pb.CreateSpecialistResponse.specialist:type_name -> pb.Specialist
	1, // 3: pb.SpecialistService.CreateSpecialist:input_type -> pb.CreateSpecialistRequest
	2, // 4: pb.SpecialistService.CreateSpecialist:output_type -> pb.CreateSpecialistResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_specialist_proto_init() }
func file_proto_specialist_proto_init() {
	if File_proto_specialist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_specialist_proto_rawDesc), len(file_proto_specialist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_specialist_proto_goTypes,
		DependencyIndexes: file_proto_specialist_proto_depIdxs,
		MessageInfos:      file_proto_specialist_proto_msgTypes,
	}.Build()
	File_proto_specialist_proto = out.File
	file_proto_specialist_proto_goTypes = nil
	file_proto_specialist_proto_depIdxs = nil
}
