// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: proto/search_specialist.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SearchSpecialistService_SearchSpecialists_FullMethodName = "/searchpb.SearchSpecialistService/SearchSpecialists"
)

// SearchSpecialistServiceClient is the client API for SearchSpecialistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchSpecialistServiceClient interface {
	SearchSpecialists(ctx context.Context, in *SearchSpecialistsRequest, opts ...grpc.CallOption) (*SearchSpecialistsResponse, error)
}

type searchSpecialistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchSpecialistServiceClient(cc grpc.ClientConnInterface) SearchSpecialistServiceClient {
	return &searchSpecialistServiceClient{cc}
}

func (c *searchSpecialistServiceClient) SearchSpecialists(ctx context.Context, in *SearchSpecialistsRequest, opts ...grpc.CallOption) (*SearchSpecialistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchSpecialistsResponse)
	err := c.cc.Invoke(ctx, SearchSpecialistService_SearchSpecialists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchSpecialistServiceServer is the server API for SearchSpecialistService service.
// All implementations must embed UnimplementedSearchSpecialistServiceServer
// for forward compatibility.
type SearchSpecialistServiceServer interface {
	SearchSpecialists(context.Context, *SearchSpecialistsRequest) (*SearchSpecialistsResponse, error)
	mustEmbedUnimplementedSearchSpecialistServiceServer()
}

// UnimplementedSearchSpecialistServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchSpecialistServiceServer struct{}

func (UnimplementedSearchSpecialistServiceServer) SearchSpecialists(context.Context, *SearchSpecialistsRequest) (*SearchSpecialistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchSpecialists not implemented")
}
func (UnimplementedSearchSpecialistServiceServer) mustEmbedUnimplementedSearchSpecialistServiceServer() {
}
func (UnimplementedSearchSpecialistServiceServer) testEmbeddedByValue() {}

// UnsafeSearchSpecialistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchSpecialistServiceServer will
// result in compilation errors.
type UnsafeSearchSpecialistServiceServer interface {
	mustEmbedUnimplementedSearchSpecialistServiceServer()
}

func RegisterSearchSpecialistServiceServer(s grpc.ServiceRegistrar, srv SearchSpecialistServiceServer) {
	// If the following call panics, it indicates UnimplementedSearchSpecialistServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchSpecialistService_ServiceDesc, srv)
}

func _SearchSpecialistService_SearchSpecialists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSpecialistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchSpecialistServiceServer).SearchSpecialists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchSpecialistService_SearchSpecialists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchSpecialistServiceServer).SearchSpecialists(ctx, req.(*SearchSpecialistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchSpecialistService_ServiceDesc is the grpc.ServiceDesc for SearchSpecialistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchSpecialistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "searchpb.SearchSpecialistService",
	HandlerType: (*SearchSpecialistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchSpecialists",
			Handler:    _SearchSpecialistService_SearchSpecialists_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/search_specialist.proto",
}
