// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/auth/features/register-credential/event_listeners/create_specialist_credential/listener/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/auth/features/register-credential/event_listeners/create_specialist_credential/listener/interface.go -destination=internal/modules/auth/features/register-credential/event_listeners/create_specialist_credential/listener/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	credential "github.com/lgustavopalmieri/healing-specialist/internal/modules/auth/domain/credential"
	provider "github.com/lgustavopalmieri/healing-specialist/pkg/healing-auth/provider"
	role "github.com/lgustavopalmieri/healing-specialist/pkg/healing-auth/role"
	gomock "go.uber.org/mock/gomock"
)

// MockCredentialRepository is a mock of CredentialRepository interface.
type MockCredentialRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialRepositoryMockRecorder
	isgomock struct{}
}

// MockCredentialRepositoryMockRecorder is the mock recorder for MockCredentialRepository.
type MockCredentialRepositoryMockRecorder struct {
	mock *MockCredentialRepository
}

// NewMockCredentialRepository creates a new mock instance.
func NewMockCredentialRepository(ctrl *gomock.Controller) *MockCredentialRepository {
	mock := &MockCredentialRepository{ctrl: ctrl}
	mock.recorder = &MockCredentialRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialRepository) EXPECT() *MockCredentialRepositoryMockRecorder {
	return m.recorder
}

// FindByEmailProviderRole mocks base method.
func (m *MockCredentialRepository) FindByEmailProviderRole(ctx context.Context, email string, p provider.Provider, r role.Role) (*credential.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmailProviderRole", ctx, email, p, r)
	ret0, _ := ret[0].(*credential.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmailProviderRole indicates an expected call of FindByEmailProviderRole.
func (mr *MockCredentialRepositoryMockRecorder) FindByEmailProviderRole(ctx, email, p, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmailProviderRole", reflect.TypeOf((*MockCredentialRepository)(nil).FindByEmailProviderRole), ctx, email, p, r)
}

// Save mocks base method.
func (m *MockCredentialRepository) Save(ctx context.Context, c *credential.Credential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCredentialRepositoryMockRecorder) Save(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCredentialRepository)(nil).Save), ctx, c)
}

// MockSetPasswordTokenGenerator is a mock of SetPasswordTokenGenerator interface.
type MockSetPasswordTokenGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockSetPasswordTokenGeneratorMockRecorder
	isgomock struct{}
}

// MockSetPasswordTokenGeneratorMockRecorder is the mock recorder for MockSetPasswordTokenGenerator.
type MockSetPasswordTokenGeneratorMockRecorder struct {
	mock *MockSetPasswordTokenGenerator
}

// NewMockSetPasswordTokenGenerator creates a new mock instance.
func NewMockSetPasswordTokenGenerator(ctrl *gomock.Controller) *MockSetPasswordTokenGenerator {
	mock := &MockSetPasswordTokenGenerator{ctrl: ctrl}
	mock.recorder = &MockSetPasswordTokenGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSetPasswordTokenGenerator) EXPECT() *MockSetPasswordTokenGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockSetPasswordTokenGenerator) Generate(ctx context.Context, subjectID string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, subjectID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Generate indicates an expected call of Generate.
func (mr *MockSetPasswordTokenGeneratorMockRecorder) Generate(ctx, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockSetPasswordTokenGenerator)(nil).Generate), ctx, subjectID)
}
