// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/search_specialist.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Specialist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Specialty     string                 `protobuf:"bytes,5,opt,name=specialty,proto3" json:"specialty,omitempty"`
	LicenseNumber string                 `protobuf:"bytes,6,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Keywords      []string               `protobuf:"bytes,8,rep,name=keywords,proto3" json:"keywords,omitempty"`
	AgreedToShare bool                   `protobuf:"varint,9,opt,name=agreed_to_share,json=agreedToShare,proto3" json:"agreed_to_share,omitempty"`
	Rating        float64                `protobuf:"fixed64,10,opt,name=rating,proto3" json:"rating,omitempty"`
	Status        string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Specialist) Reset() {
	*x = Specialist{}
	mi := &file_proto_search_specialist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Specialist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specialist) ProtoMessage() {}

func (x *Specialist) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_specialist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specialist.ProtoReflect.Descriptor instead.
func (*Specialist) Descriptor() ([]byte, []int) {
	return file_proto_search_specialist_proto_rawDescGZIP(), []int{0}
}

func (x *Specialist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Specialist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Specialist) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Specialist) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Specialist) GetSpecialty() string {
	if x != nil {
		return x.Specialty
	}
	return ""
}

func (x *Specialist) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *Specialist) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Specialist) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *Specialist) GetAgreedToShare() bool {
	if x != nil {
		return x.AgreedToShare
	}
	return false
}

func (x *Specialist) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Specialist) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Specialist) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Specialist) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SearchFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFilter) Reset() {
	*x = SearchFilter{}
	mi := &file_proto_search_specialist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFilter) ProtoMessage() {}

func (x *SearchFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_specialist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFilter.ProtoReflect.Descriptor instead.
func (*SearchFilter) Descriptor() ([]byte, []int) {
	return file_proto_search_specialist_proto_rawDescGZIP(), []int{1}
}

func (x *SearchFilter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SearchFilter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SortCriteria struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Order         string                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortCriteria) Reset() {
	*x = SortCriteria{}
	mi := &file_proto_search_specialist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortCriteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortCriteria) ProtoMessage() {}

func (x *SortCriteria) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_specialist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortCriteria.ProtoReflect.Descriptor instead.
func (*SortCriteria) Descriptor() ([]byte, []int) {
	return file_proto_search_specialist_proto_rawDescGZIP(), []int{2}
}

func (x *SortCriteria) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SortCriteria) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

type SearchSpecialistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchTerm    string                 `protobuf:"bytes,1,opt,name=search_term,json=searchTerm,proto3" json:"search_term,omitempty"`
	Filters       []*SearchFilter        `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
	Sort          []*SortCriteria        `protobuf:"bytes,3,rep,name=sort,proto3" json:"sort,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Cursor        string                 `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Direction     string                 `protobuf:"bytes,6,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSpecialistsRequest) Reset() {
	*x = SearchSpecialistsRequest{}
	mi := &file_proto_search_specialist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSpecialistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSpecialistsRequest) ProtoMessage() {}

func (x *SearchSpecialistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_specialist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSpecialistsRequest.ProtoReflect.Descriptor instead.
func (*SearchSpecialistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_specialist_proto_rawDescGZIP(), []int{3}
}

func (x *SearchSpecialistsRequest) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

func (x *SearchSpecialistsRequest) GetFilters() []*SearchFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SearchSpecialistsRequest) GetSort() []*SortCriteria {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *SearchSpecialistsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchSpecialistsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *SearchSpecialistsRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type PaginationInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NextCursor       string                 `protobuf:"bytes,1,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	PreviousCursor   string                 `protobuf:"bytes,2,opt,name=previous_cursor,json=previousCursor,proto3" json:"previous_cursor,omitempty"`
	HasNextPage      bool                   `protobuf:"varint,3,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	HasPreviousPage  bool                   `protobuf:"varint,4,opt,name=has_previous_page,json=hasPreviousPage,proto3" json:"has_previous_page,omitempty"`
	TotalItemsInPage int32                  `protobuf:"varint,5,opt,name=total_items_in_page,json=totalItemsInPage,proto3" json:"total_items_in_page,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PaginationInfo) Reset() {
	*x = PaginationInfo{}
	mi := &file_proto_search_specialist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationInfo) ProtoMessage() {}

func (x *PaginationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_specialist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationInfo.ProtoReflect.Descriptor instead.
func (*PaginationInfo) Descriptor() ([]byte, []int) {
	return file_proto_search_specialist_proto_rawDescGZIP(), []int{4}
}

func (x *PaginationInfo) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *PaginationInfo) GetPreviousCursor() string {
	if x != nil {
		return x.PreviousCursor
	}
	return ""
}

func (x *PaginationInfo) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

func (x *PaginationInfo) GetHasPreviousPage() bool {
	if x != nil {
		return x.HasPreviousPage
	}
	return false
}

func (x *PaginationInfo) GetTotalItemsInPage() int32 {
	if x != nil {
		return x.TotalItemsInPage
	}
	return 0
}

type SearchSpecialistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Specialists   []*Specialist          `protobuf:"bytes,1,rep,name=specialists,proto3" json:"specialists,omitempty"`
	Pagination    *PaginationInfo        `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSpecialistsResponse) Reset() {
	*x = SearchSpecialistsResponse{}
	mi := &file_proto_search_specialist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSpecialistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSpecialistsResponse) ProtoMessage() {}

func (x *SearchSpecialistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_specialist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSpecialistsResponse.ProtoReflect.Descriptor instead.
func (*SearchSpecialistsResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_specialist_proto_rawDescGZIP(), []int{5}
}

func (x *SearchSpecialistsResponse) GetSpecialists() []*Specialist {
	if x != nil {
		return x.Specialists
	}
	return nil
}

func (x *SearchSpecialistsResponse) GetPagination() *PaginationInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_proto_search_specialist_proto protoreflect.FileDescriptor

const file_proto_search_specialist_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/search_specialist.proto\x12\bsearchpb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xad\x03\n" +
	"\n" +
	"Specialist\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1c\n" +
	"\tspecialty\x18\x05 \x01(\tR\tspecialty\x12%\n" +
	"\x0elicense_number\x18\x06 \x01(\tR\rlicenseNumber\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1a\n" +
	"\bkeywords\x18\b \x03(\tR\bkeywords\x12&\n" +
	"\x0fagreed_to_share\x18\t \x01(\bR\ragreedToShare\x12\x16\n" +
	"\x06rating\x18\n" +
	" \x01(\x01R\x06rating\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\":\n" +
	"\fSearchFilter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\":\n" +
	"\fSortCriteria\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x14\n" +
	"\x05order\x18\x02 \x01(\tR\x05order\"\xec\x01\n" +
	"\x18SearchSpecialistsRequest\x12\x1f\n" +
	"\vsearch_term\x18\x01 \x01(\tR\n" +
	"searchTerm\x120\n" +
	"\afilters\x18\x02 \x03(\v2\x16.searchpb.SearchFilterR\afilters\x12*\n" +
	"\x04sort\x18\x03 \x03(\v2\x16.searchpb.SortCriteriaR\x04sort\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06cursor\x18\x05 \x01(\tR\x06cursor\x12\x1c\n" +
	"\tdirection\x18\x06 \x01(\tR\tdirection\"\xd9\x01\n" +
	"\x0ePaginationInfo\x12\x1f\n" +
	"\vnext_cursor\x18\x01 \x01(\tR\n" +
	"nextCursor\x12'\n" +
	"\x0fprevious_cursor\x18\x02 \x01(\tR\x0epreviousCursor\x12\"\n" +
	"\rhas_next_page\x18\x03 \x01(\bR\vhasNextPage\x12*\n" +
	"\x11has_previous_page\x18\x04 \x01(\bR\x0fhasPreviousPage\x12-\n" +
	"\x13total_items_in_page\x18\x05 \x01(\x05R\x10totalItemsInPage\"\x8d\x01\n" +
	"\x19SearchSpecialistsResponse\x126\n" +
	"\vspecialists\x18\x01 \x03(\v2\x14.searchpb.SpecialistR\vspecialists\x128\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x18.searchpb.PaginationInfoR\n" +
	"pagination2y\n" +
	"\x17SearchSpecialistService\x12^\n" +
	"\x11SearchSpecialists\x12\".searchpb.SearchSpecialistsRequest\x1a#.searchpb.SearchSpecialistsResponse\"\x00B\x06Z\x04./pbb\x06proto3"

var (
	file_proto_search_specialist_proto_rawDescOnce sync.Once
	file_proto_search_specialist_proto_rawDescData []byte
)

func file_proto_search_specialist_proto_rawDescGZIP() []byte {
	file_proto_search_specialist_proto_rawDescOnce.Do(func() {
		file_proto_search_specialist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_search_specialist_proto_rawDesc), len(file_proto_search_specialist_proto_rawDesc)))
	})
	return file_proto_search_specialist_proto_rawDescData
}

var file_proto_search_specialist_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_search_specialist_proto_goTypes = []any{
	(*Specialist)(nil),                // 0: searchpb.Specialist
	(*SearchFilter)(nil),              // 1: searchpb.SearchFilter
	(*SortCriteria)(nil),              // 2: searchpb.SortCriteria
	(*SearchSpecialistsRequest)(nil),  // 3: searchpb.SearchSpecialistsRequest
	(*PaginationInfo)(nil),            // 4: searchpb.PaginationInfo
	(*SearchSpecialistsResponse)(nil), // 5: searchpb.SearchSpecialistsResponse
	(*timestamp.Timestamp)(nil),       // 6: google.protobuf.Timestamp
}
var file_proto_search_specialist_proto_depIdxs = []int32{
	6, // 0: searchpb.Specialist.created_at:type_name -> google.protobuf.Timestamp
	6, // 1: searchpb.Specialist.updated_at:type_name -> google.protobuf.Timestamp
	1, // 2: searchpb.SearchSpecialistsRequest.filters:type_name -> searchpb.SearchFilter
	2, // 3: searchpb.SearchSpecialistsRequest.sort:type_name -> searchpb.SortCriteria
	0, // 4: searchpb.SearchSpecialistsResponse.specialists:type_name -> searchpb.Specialist
	4, // 5: searchpb.SearchSpecialistsResponse.pagination:type_name -> searchpb.PaginationInfo
	3, // 6: searchpb.SearchSpecialistService.SearchSpecialists:input_type -> searchpb.SearchSpecialistsRequest
	5, // 7: searchpb.SearchSpecialistService.SearchSpecialists:output_type -> searchpb.SearchSpecialistsResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_search_specialist_proto_init() }
func file_proto_search_specialist_proto_init() {
	if File_proto_search_specialist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_search_specialist_proto_rawDesc), len(file_proto_search_specialist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_search_specialist_proto_goTypes,
		DependencyIndexes: file_proto_search_specialist_proto_depIdxs,
		MessageInfos:      file_proto_search_specialist_proto_msgTypes,
	}.Build()
	File_proto_search_specialist_proto = out.File
	file_proto_search_specialist_proto_goTypes = nil
	file_proto_search_specialist_proto_depIdxs = nil
}
