// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/specialist/features/create/adapters/inbound/http_handler/handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/specialist/features/create/adapters/inbound/http_handler/handler.go -destination=internal/modules/specialist/features/create/adapters/inbound/http_handler/mocks/usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/lgustavopalmieri/healing-specialist/internal/modules/specialist/domain"
	application "github.com/lgustavopalmieri/healing-specialist/internal/modules/specialist/features/create/application"
	gomock "go.uber.org/mock/gomock"
)

// MockSpecialistCreateUseCaseInterface is a mock of SpecialistCreateUseCaseInterface interface.
type MockSpecialistCreateUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSpecialistCreateUseCaseInterfaceMockRecorder
	isgomock struct{}
}

// MockSpecialistCreateUseCaseInterfaceMockRecorder is the mock recorder for MockSpecialistCreateUseCaseInterface.
type MockSpecialistCreateUseCaseInterfaceMockRecorder struct {
	mock *MockSpecialistCreateUseCaseInterface
}

// NewMockSpecialistCreateUseCaseInterface creates a new mock instance.
func NewMockSpecialistCreateUseCaseInterface(ctrl *gomock.Controller) *MockSpecialistCreateUseCaseInterface {
	mock := &MockSpecialistCreateUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockSpecialistCreateUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpecialistCreateUseCaseInterface) EXPECT() *MockSpecialistCreateUseCaseInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockSpecialistCreateUseCaseInterface) Execute(ctx context.Context, input application.CreateSpecialistDTO) (*domain.Specialist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*domain.Specialist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockSpecialistCreateUseCaseInterfaceMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockSpecialistCreateUseCaseInterface)(nil).Execute), ctx, input)
}
