// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/auth/features/set-password/application/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/auth/features/set-password/application/interface.go -destination=internal/modules/auth/features/set-password/application/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	audit "github.com/lgustavopalmieri/healing-specialist/internal/modules/auth/domain/audit"
	credential "github.com/lgustavopalmieri/healing-specialist/internal/modules/auth/domain/credential"
	session "github.com/lgustavopalmieri/healing-specialist/internal/modules/auth/domain/session"
	tokenpair "github.com/lgustavopalmieri/healing-specialist/internal/modules/auth/domain/token_pair"
	application "github.com/lgustavopalmieri/healing-specialist/internal/modules/auth/features/set-password/application"
	refreshtoken "github.com/lgustavopalmieri/healing-specialist/internal/modules/auth/shared/repositories/refresh_token"
	role "github.com/lgustavopalmieri/healing-specialist/pkg/healing-auth/role"
	gomock "go.uber.org/mock/gomock"
)

// MockSetPasswordTokenValidator is a mock of SetPasswordTokenValidator interface.
type MockSetPasswordTokenValidator struct {
	ctrl     *gomock.Controller
	recorder *MockSetPasswordTokenValidatorMockRecorder
	isgomock struct{}
}

// MockSetPasswordTokenValidatorMockRecorder is the mock recorder for MockSetPasswordTokenValidator.
type MockSetPasswordTokenValidatorMockRecorder struct {
	mock *MockSetPasswordTokenValidator
}

// NewMockSetPasswordTokenValidator creates a new mock instance.
func NewMockSetPasswordTokenValidator(ctrl *gomock.Controller) *MockSetPasswordTokenValidator {
	mock := &MockSetPasswordTokenValidator{ctrl: ctrl}
	mock.recorder = &MockSetPasswordTokenValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSetPasswordTokenValidator) EXPECT() *MockSetPasswordTokenValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockSetPasswordTokenValidator) Validate(ctx context.Context, rawToken string) (*application.ValidatedSetPasswordToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, rawToken)
	ret0, _ := ret[0].(*application.ValidatedSetPasswordToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockSetPasswordTokenValidatorMockRecorder) Validate(ctx, rawToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockSetPasswordTokenValidator)(nil).Validate), ctx, rawToken)
}

// MockSingleUseTokenRepository is a mock of SingleUseTokenRepository interface.
type MockSingleUseTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSingleUseTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockSingleUseTokenRepositoryMockRecorder is the mock recorder for MockSingleUseTokenRepository.
type MockSingleUseTokenRepositoryMockRecorder struct {
	mock *MockSingleUseTokenRepository
}

// NewMockSingleUseTokenRepository creates a new mock instance.
func NewMockSingleUseTokenRepository(ctrl *gomock.Controller) *MockSingleUseTokenRepository {
	mock := &MockSingleUseTokenRepository{ctrl: ctrl}
	mock.recorder = &MockSingleUseTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSingleUseTokenRepository) EXPECT() *MockSingleUseTokenRepositoryMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockSingleUseTokenRepository) Consume(ctx context.Context, jti string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, jti)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Consume indicates an expected call of Consume.
func (mr *MockSingleUseTokenRepositoryMockRecorder) Consume(ctx, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockSingleUseTokenRepository)(nil).Consume), ctx, jti)
}

// MockCredentialRepository is a mock of CredentialRepository interface.
type MockCredentialRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialRepositoryMockRecorder
	isgomock struct{}
}

// MockCredentialRepositoryMockRecorder is the mock recorder for MockCredentialRepository.
type MockCredentialRepositoryMockRecorder struct {
	mock *MockCredentialRepository
}

// NewMockCredentialRepository creates a new mock instance.
func NewMockCredentialRepository(ctrl *gomock.Controller) *MockCredentialRepository {
	mock := &MockCredentialRepository{ctrl: ctrl}
	mock.recorder = &MockCredentialRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialRepository) EXPECT() *MockCredentialRepositoryMockRecorder {
	return m.recorder
}

// FindBySubjectAndRole mocks base method.
func (m *MockCredentialRepository) FindBySubjectAndRole(ctx context.Context, subjectID string, r role.Role) (*credential.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySubjectAndRole", ctx, subjectID, r)
	ret0, _ := ret[0].(*credential.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySubjectAndRole indicates an expected call of FindBySubjectAndRole.
func (mr *MockCredentialRepositoryMockRecorder) FindBySubjectAndRole(ctx, subjectID, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySubjectAndRole", reflect.TypeOf((*MockCredentialRepository)(nil).FindBySubjectAndRole), ctx, subjectID, r)
}

// UpdateWithSessionInTransaction mocks base method.
func (m *MockCredentialRepository) UpdateWithSessionInTransaction(ctx context.Context, cred *credential.Credential, sess *session.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWithSessionInTransaction", ctx, cred, sess)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWithSessionInTransaction indicates an expected call of UpdateWithSessionInTransaction.
func (mr *MockCredentialRepositoryMockRecorder) UpdateWithSessionInTransaction(ctx, cred, sess any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithSessionInTransaction", reflect.TypeOf((*MockCredentialRepository)(nil).UpdateWithSessionInTransaction), ctx, cred, sess)
}

// MockAccessTokenIssuer is a mock of AccessTokenIssuer interface.
type MockAccessTokenIssuer struct {
	ctrl     *gomock.Controller
	recorder *MockAccessTokenIssuerMockRecorder
	isgomock struct{}
}

// MockAccessTokenIssuerMockRecorder is the mock recorder for MockAccessTokenIssuer.
type MockAccessTokenIssuerMockRecorder struct {
	mock *MockAccessTokenIssuer
}

// NewMockAccessTokenIssuer creates a new mock instance.
func NewMockAccessTokenIssuer(ctrl *gomock.Controller) *MockAccessTokenIssuer {
	mock := &MockAccessTokenIssuer{ctrl: ctrl}
	mock.recorder = &MockAccessTokenIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessTokenIssuer) EXPECT() *MockAccessTokenIssuerMockRecorder {
	return m.recorder
}

// IssueAccessAndRefresh mocks base method.
func (m *MockAccessTokenIssuer) IssueAccessAndRefresh(ctx context.Context, c *credential.Credential) (*tokenpair.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueAccessAndRefresh", ctx, c)
	ret0, _ := ret[0].(*tokenpair.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueAccessAndRefresh indicates an expected call of IssueAccessAndRefresh.
func (mr *MockAccessTokenIssuerMockRecorder) IssueAccessAndRefresh(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueAccessAndRefresh", reflect.TypeOf((*MockAccessTokenIssuer)(nil).IssueAccessAndRefresh), ctx, c)
}

// MockRefreshTokenRepository is a mock of RefreshTokenRepository interface.
type MockRefreshTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockRefreshTokenRepositoryMockRecorder is the mock recorder for MockRefreshTokenRepository.
type MockRefreshTokenRepositoryMockRecorder struct {
	mock *MockRefreshTokenRepository
}

// NewMockRefreshTokenRepository creates a new mock instance.
func NewMockRefreshTokenRepository(ctrl *gomock.Controller) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockRefreshTokenRepository) Save(ctx context.Context, refreshTokenHash string, payload refreshtoken.RefreshTokenPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, refreshTokenHash, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRefreshTokenRepositoryMockRecorder) Save(ctx, refreshTokenHash, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRefreshTokenRepository)(nil).Save), ctx, refreshTokenHash, payload)
}

// MockAuditRepository is a mock of AuditRepository interface.
type MockAuditRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuditRepositoryMockRecorder
	isgomock struct{}
}

// MockAuditRepositoryMockRecorder is the mock recorder for MockAuditRepository.
type MockAuditRepositoryMockRecorder struct {
	mock *MockAuditRepository
}

// NewMockAuditRepository creates a new mock instance.
func NewMockAuditRepository(ctrl *gomock.Controller) *MockAuditRepository {
	mock := &MockAuditRepository{ctrl: ctrl}
	mock.recorder = &MockAuditRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditRepository) EXPECT() *MockAuditRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockAuditRepository) Save(ctx context.Context, log *audit.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAuditRepositoryMockRecorder) Save(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAuditRepository)(nil).Save), ctx, log)
}
