// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lgustavopalmieri/healing-specialist/internal/modules/auth/features/login/adapters/inbound/http_handler (interfaces: LoginUseCaseInterface)
//
// Generated by this command:
//
//	mockgen -destination=internal/modules/auth/features/login/adapters/inbound/http_handler/mocks/usecase_mock.go -package=mocks github.com/lgustavopalmieri/healing-specialist/internal/modules/auth/features/login/adapters/inbound/http_handler LoginUseCaseInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	application "github.com/lgustavopalmieri/healing-specialist/internal/modules/auth/features/login/application"
	gomock "go.uber.org/mock/gomock"
)

// MockLoginUseCaseInterface is a mock of LoginUseCaseInterface interface.
type MockLoginUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockLoginUseCaseInterfaceMockRecorder
	isgomock struct{}
}

// MockLoginUseCaseInterfaceMockRecorder is the mock recorder for MockLoginUseCaseInterface.
type MockLoginUseCaseInterfaceMockRecorder struct {
	mock *MockLoginUseCaseInterface
}

// NewMockLoginUseCaseInterface creates a new mock instance.
func NewMockLoginUseCaseInterface(ctrl *gomock.Controller) *MockLoginUseCaseInterface {
	mock := &MockLoginUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockLoginUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginUseCaseInterface) EXPECT() *MockLoginUseCaseInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockLoginUseCaseInterface) Execute(ctx context.Context, input application.LoginDTO) (*application.LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*application.LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockLoginUseCaseInterfaceMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockLoginUseCaseInterface)(nil).Execute), ctx, input)
}
