// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/auth/features/set-password/adapters/inbound/http_handler/handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/auth/features/set-password/adapters/inbound/http_handler/handler.go -destination=internal/modules/auth/features/set-password/adapters/inbound/http_handler/mocks/usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	application "github.com/lgustavopalmieri/healing-specialist/internal/modules/auth/features/set-password/application"
	gomock "go.uber.org/mock/gomock"
)

// MockSetPasswordUseCaseInterface is a mock of SetPasswordUseCaseInterface interface.
type MockSetPasswordUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSetPasswordUseCaseInterfaceMockRecorder
	isgomock struct{}
}

// MockSetPasswordUseCaseInterfaceMockRecorder is the mock recorder for MockSetPasswordUseCaseInterface.
type MockSetPasswordUseCaseInterfaceMockRecorder struct {
	mock *MockSetPasswordUseCaseInterface
}

// NewMockSetPasswordUseCaseInterface creates a new mock instance.
func NewMockSetPasswordUseCaseInterface(ctrl *gomock.Controller) *MockSetPasswordUseCaseInterface {
	mock := &MockSetPasswordUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockSetPasswordUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSetPasswordUseCaseInterface) EXPECT() *MockSetPasswordUseCaseInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockSetPasswordUseCaseInterface) Execute(ctx context.Context, input application.SetPasswordDTO) (*application.SetPasswordResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*application.SetPasswordResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockSetPasswordUseCaseInterfaceMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockSetPasswordUseCaseInterface)(nil).Execute), ctx, input)
}
